version: '3.8'

services:
  backend:
    container_name: backend-dc
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
    working_dir: /app
    command: sh -c "npm run dev"
    depends_on:
      - database

  database:
    image: mariadb:latest
    container_name: database-dc
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}

volumes:
  mariadb_data:
