version: '3.8'

services:
  backend:
    container_name: backend-dc
    image: node:latest
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/
    working_dir: /app
    command: sh -c "npm run dev"

  database:
    image: mariadb:latest
    container_name: database-dc
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
